print("Digite a nota 1")
entrada1 = int(input())
print("Digite a nota 2")
entrada2 = int(input())
print("Digite a nota 3")
entrada3 = int(input())
print("Digite a nota 4")
entrada4 = int(input())
print("Digite a nota 5")
entrada5 = int(input())
soma = entrada1 + entrada2 + entrada3 + entrada4 + entrada5
print(soma/5)